// automatically generated by the FlatBuffers compiler, do not modify

namespace fb
{

public enum Command : int
{
    NotSet = 0,
    HealthCheckRequest = 1,
    HealthCheckResponse = 2,
    NotifyMatchRequest = 10,
    NotifyMatchResponse = 11,
    MatchRequest = 12,
    MatchResponse = 13,
    MatchingServerIDRequest = 30,
    MatchingServerIDResponse = 31,
    MatchingServerListRequest = 32,
    MatchingServerListResponse = 33,
    RoomCreateRequest = 40,
    RoomCreateResponse = 41,
    RoomJoinRequest = 50,
    RoomJoinResponse = 51,
    GameStart = 52,
    GameEnd = 53,
    PacketGeneratorStart = 60,
    PacketGeneratorEnd = 61,
    PacketGeneratorDummy = 62,
};


}
